# Generated by Django 5.0.6 on 2024-05-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='description',
        ),
    ]
