# Generated by Django 5.0.6 on 2024-05-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_todo', '0002_rename_content_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
