# Generated by Django 5.0.6 on 2024-05-16 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_todo', '0006_alter_task_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 5, 16)),
            preserve_default=False,
        ),
    ]
