# Generated by Django 5.0.6 on 2024-05-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_todo', '0007_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
    ]
